checks:
  php:
    code_rating: true
    duplication: true

build:
  nodes:
    coverage:
      tests:
        override:
          - command: 'phpunit --coverage-clover=clover.xml'
            coverage:
              file: 'clover.xml'
              format: 'clover'
